[package]
name = "gsy-ethers-listener"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { workspace = true, features = ["ws", "abigen", "rustls"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
async-trait = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
hex = { workspace = true }

[dev-dependencies]
ethers = { workspace = true, features = ["ws", "abigen", "rustls", "solc"] }
tokio = { workspace = true, features = ["full"] }
tempfile = { workspace = true }
