services:
  gsy-orderbook:
    container_name: gsy-orderbook
    build:
      context: ..
      dockerfile: ./gsy-orderbook-service/Dockerfile
    depends_on:
      mongodb:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - CARGO_HOME=/var/www/orderbook/.cargo
      - APPLICATION_HOST=0.0.0.0
      - APPLICATION_PORT=8080
      - DATABASE_NAME=orderbook
      - DATABASE_HOST=mongodb
      - DATABASE_URL_SCHEME=mongodb
      - DATABASE_USERNAME=gsy
      - DATABASE_PASSWORD=gsy
      - NODE_URL=
      - SCHEDULER_INTERVAL=900

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - ~/mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gsy
      - MONGO_INITDB_ROOT_PASSWORD=gsy
