[package]
name = "primitives"
version = "0.1.0"
edition = "2021"

[lib]
name = "primitives"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
blake2 = "0.10"
chrono = { workspace = true }
hex = { workspace = true }
once_cell = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["time"] }
tracing = { workspace = true }
tracing-bunyan-formatter = "0.3.10"
tracing-log = "0.2.0"
tracing-subscriber = { workspace = true, features = ["env-filter"] }
thiserror = "2.0.19"

[dev-dependencies]
wiremock = "0.6.5"
