[workspace]
resolver = "2"

members = [
    "offchain-primitives",
    "gsy-community-client",
    "gsy-execution-engine",
    "gsy-market-orchestrator",
    "gsy-matching-engine",
    "gsy-offchain-storage",
    "e2e-tests",
]

exclude = [
    "gsy-node",
    "primitives",
    "primitives/test-helpers",
]
