services:
  gsy-node:
    container_name: gsy-node
    build:
      dockerfile: ./gsy-node/Dockerfile
    #image: gsy-node:latest
    depends_on:
      gsy-matching-engine:
        condition: service_started
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/gsy-node/.cargo
      - ORDERBOOK_SERVICE_URL=http://gsy-orderbook:8080

  gsy-orderbook:
    container_name: gsy-orderbook
    build:
      dockerfile: ./gsy-orderbook-service/Dockerfile
    depends_on:
      mongodb:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - CARGO_HOME=/var/www/orderbook/.cargo
      - APPLICATION_HOST=0.0.0.0
      - APPLICATION_PORT=8080
      - DATABASE_NAME=orderbook
      - DATABASE_HOST=mongodb
      - DATABASE_URL_SCHEME=mongodb
      - DATABASE_USERNAME=gsy
      - DATABASE_PASSWORD=gsy
      - NODE_URL=gsy-node:9944
      - SCHEDULER_INTERVAL=900

  gsy-matching-engine:
    container_name: gsy-matching-engine
    build:
      dockerfile: ./gsy-matching-engine/Dockerfile
    depends_on:
      gsy-orderbook:
        condition: service_started
    working_dir: /var/www/matching-engine

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - ~/mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gsy
      - MONGO_INITDB_ROOT_PASSWORD=gsy