version: "3.2"

services:
  dev:
    container_name: gsy-node
    image: gsy_dex_image:staging
    working_dir: /var/www/gsy-node
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/gsy-node/.cargo
    volumes:
      - ./gsy-node:/var/www/gsy-node
    command: bash -c "cargo build --release && ./target/release/gsy-node --dev --ws-external"

  orderbook:
    container_name: orderbook
    image: gsy_dex_image:staging
    build:
      dockerfile: Dockerfile
    depends_on:
      mongodb:
        condition: service_started
    working_dir: /var/www/orderbook
    ports:
      - "8080:8080"
    environment:
      - CARGO_HOME=/var/www/orderbook/.cargo
      - APPLICATION_HOST=0.0.0.0
      - APPLICATION_PORT=8080
      - DATABASE_NAME=orderbook
      - DATABASE_HOST=mongodb
      - DATABASE_URL_SCHEME=mongodb
      - DATABASE_USERNAME=gsy
      - DATABASE_PASSWORD=gsy
      - NODE_URL=gsy-node:9944
      - SCHEDULER_INTERVAL=900
    volumes:
      - ./gsy-orderbook-service:/var/www/orderbook
    command: bash -c "cargo build --release && ./target/release/gsy-orderbook-service"

  mongodb:
    image: mongo:5.0
    ports:
      - "27018:27017"
    volumes:
      - ~/mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gsy
      - MONGO_INITDB_ROOT_PASSWORD=gsy