services:

  mongodb:
    image: mongo:8.3.8
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gsy
      - MONGO_INITDB_ROOT_PASSWORD=gsy

  gsy-primitives-integration-test:
    container_name: gsy-primitives-integration-test
    build:
      context: .
      dockerfile: primitives/Dockerfile
      target: builder
    command: cargo test
    working_dir: /var/www/primitives
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=1

  gsy-contracts-tests:
    container_name: gsy-contracts-tests
    build:
      context: ./gsy-contracts
      dockerfile: Dockerfile
    command: npx hardhat test
    volumes:
      - ./gsy-contracts:/app
      - /app/node_modules

  gsy-listener-test:
    container_name: gsy-listener-test
    build:
      context: ./gsy-ethers-listener
      dockerfile: Dockerfile
    entrypoint: ["cargo", "test"]
    environment:
      - RUST_LOG=info

  gsy-offchain-storage-integration-test:
    container_name: gsy-offchain-storage-integration-test
    build:
      context: .
      dockerfile: gsy-offchain-storage/Dockerfile
      target: builder
    entrypoint: ["cargo", "test", "--release"]
    working_dir: /var/www/gsy-offchain-storage
    depends_on:
      mongodb:
        condition: service_started
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info
      - DATABASE_HOST=mongodb
      - DATABASE_NAME=test_db
      - DATABASE_USERNAME=gsy
      - DATABASE_PASSWORD=gsy
      - DATABASE_URL_SCHEME=mongodb
      - APPLICATION_HOST=0.0.0.0
      - APPLICATION_PORT=8080
      - SCHEDULER_INTERVAL=900
      - EVM_NODE_URL=ws://localhost:8545

  gsy-market-orchestrator-integration-test:
    container_name: gsy-market-orchestrator-integration-test
    build:
      context: .
      dockerfile: gsy-market-orchestrator/Dockerfile
    entrypoint: ["cargo", "test", "--release"]
    working_dir: /var/www/gsy-market-orchestrator
    environment:
      - RUST_LOG=info

  gsy-matching-engine-integration-test:
    container_name: gsy-matching-engine-integration-test
    build:
      context: .
      dockerfile: gsy-matching-engine/Dockerfile
      target: builder
    command: cargo test --release
    working_dir: /var/www/gsy-matching-engine
    environment:
      - RUST_LOG=info

  gsy-execution-engine-integration-test:
    container_name: gsy-execution-engine-integration-test
    build:
      context: .
      dockerfile: gsy-execution-engine/Dockerfile
      target: builder
    command: cargo test --release
    working_dir: /var/www/gsy-execution-engine
    environment:
      - RUST_LOG=info

  gsy-community-client-integration-test:
    container_name: gsy-community-client-integration-test
    build:
      context: .
      dockerfile: gsy-community-client/Dockerfile
      target: builder
    command: cargo test --release
    working_dir: /var/www/gsy-community-client
    environment:
      - RUST_LOG=info
