[package]
name = "gsy-market-orchestrator"
version = "0.1.0"
authors = ["Grid Singularity <info@gridsingularity.com>"]
edition = "2021"

[[bin]]
path = "src/main.rs"
name = "gsy-market-orchestrator"

[dependencies]
primitives = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
envy = "0.4"
ethers = { workspace = true, features = ["ws", "rustls", "solc"] }
reqwest = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
tracing = { workspace = true, features = ["log"] }
tracing-subscriber = { workspace = true, features = ["registry", "env-filter"] }
once_cell = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
