use crate::algorithms::MatchOrders;
use crate::models::{Attributes, BidOfferMatch, MatchingData, Order, Requirements};
use anyhow::{anyhow, Error, Result};
use ethers::prelude::*;
use ethers::utils::keccak256;
use primitives::db_api_schema::orders::{
    energy_type_to_contract, DbOrderSchema, EnergyType, OrderEnum, OrderStatus,
};
use primitives::ewds::dto::EwdsOrderDto;
use primitives::ewds::{EwdsClient, EwdsOperation};
use primitives::matching::matching_block_interval;
use primitives::utils::{bytes16_to_hex, parse_uuid_or_hex_bytes16, NODE_FLOAT_SCALING_FACTOR};
use primitives::MatchingAlgorithm;
use std::collections::{BTreeMap, HashMap};
use std::env;
use std::str::FromStr;
use tokio::time::{sleep, Duration};
use tracing::{error, info, warn};
use uuid::Uuid;

abigen!(
    SettleOrderBatchContract,
    "src/connectors/abi/settle_order_batch.json"
);

type EvmOrderDataTuple = ([u8; 16], [u8; 16], [u8; 16], u64, u64, u64, u64, u8, u8);
type EvmMatchTuple = (
    [u8; 16],
    EvmOrderDataTuple,
    EvmOrderDataTuple,
    [u8; 16],
    [u8; 16],
    U256,
    U256,
);

struct PreparedOrders {
    open_bids: Vec<Order>,
    open_offers: Vec<Order>,
    by_order_id: HashMap<String, DbOrderSchema>,
}

pub async fn evm_subscribe(
    orderbook_url: String,
    node_url: String,
    settle_order_batch_address: String,
    matching_engine_private_key: String,
    matching_algorithm: MatchingAlgorithm,
) -> Result<(), Error> {
    info!("Connecting to EVM node {}", node_url);
    let provider = Provider::<Ws>::connect(node_url.as_str()).await?;
    let matching_block_interval = matching_block_interval();
    info!(
        "Using {}-block matching interval for {}",
        matching_block_interval, matching_algorithm
    );
    let mut last_processed_block = provider.get_block_number().await?;
    // Keep track of which trigger "bucket" was already processed, so we do not
    // miss matches when multiple blocks are mined between polling iterations.
    let mut last_processed_trigger_bucket =
        last_processed_block.as_u64().saturating_sub(1) / matching_block_interval;

    loop {
        let block_number = provider.get_block_number().await?;
        if block_number > last_processed_block {
            info!("Block {} observed", block_number);

            let current_trigger_bucket = block_number.as_u64() / matching_block_interval;
            if current_trigger_bucket > last_processed_trigger_bucket {
                info!(
                    "Matching trigger reached (bucket {} -> {}) at block {}",
                    last_processed_trigger_bucket, current_trigger_bucket, block_number
                );

                if let Err(error) = run_matching_cycle(
                    orderbook_url.as_str(),
                    node_url.as_str(),
                    settle_order_batch_address.as_str(),
                    matching_engine_private_key.as_str(),
                    &matching_algorithm,
                )
                .await
                {
                    error!("Matching cycle failed: {:?}", error);
                }

                last_processed_trigger_bucket = current_trigger_bucket;
            }

            last_processed_block = block_number;
        }

        sleep(Duration::from_secs(2)).await;
    }
}

async fn run_matching_cycle(
    orderbook_url: &str,
    evm_node_url: &str,
    settle_order_batch_address: &str,
    matching_engine_private_key: &str,
    matching_algorithm: &MatchingAlgorithm,
) -> Result<()> {
    info!("Starting matching cycle");
    info!("Fetching open orders from {}", orderbook_url);

    let prepared_orders =
        fetch_open_orders_from_orderbook_service(orderbook_url.to_string()).await?;
    info!(
        "Prepared open orders: bids={}, offers={}",
        prepared_orders.open_bids.len(),
        prepared_orders.open_offers.len()
    );
    if prepared_orders.open_bids.is_empty() || prepared_orders.open_offers.is_empty() {
        info!("No open bid/offer pairs to match");
        return Ok(());
    }

    let PreparedOrders {
        open_bids,
        open_offers,
        by_order_id,
    } = prepared_orders;
    let order_books = partition_orders_by_market_slot(open_bids, open_offers)?;
    info!(
        "Partitioned open orders into {} market/time-slot order books",
        order_books.len()
    );

    let bid_offer_matches = match_order_books(order_books, matching_algorithm)?;
    if bid_offer_matches.is_empty() {
        info!("No matches generated by {} algorithm", matching_algorithm);
        return Ok(());
    }

    info!(
        "Generated {} total matches using {}",
        bid_offer_matches.len(),
        matching_algorithm
    );
    send_settle_batch_transaction(
        evm_node_url,
        settle_order_batch_address,
        matching_engine_private_key,
        bid_offer_matches,
        by_order_id,
    )
    .await?;
    Ok(())
}

fn match_order_books(
    order_books: Vec<MatchingData>,
    matching_algorithm: &MatchingAlgorithm,
) -> Result<Vec<BidOfferMatch>> {
    let mut bid_offer_matches = Vec::new();
    for mut matching_data in order_books {
        if matching_data.bids().is_empty() || matching_data.offers().is_empty() {
            info!(
                "Skipping market {} timeslot {} without an open bid/offer pair",
                matching_data.market_id(),
                matching_data.time_slot()
            );
            continue;
        }

        let matches = matching_algorithm
            .match_orders(&mut matching_data)
            .map_err(|error| anyhow!(error))?;
        info!(
            "Generated {} matches for market {} timeslot {} using {}",
            matches.len(),
            matching_data.market_id(),
            matching_data.time_slot(),
            matching_algorithm
        );
        bid_offer_matches.extend(matches);
    }

    Ok(bid_offer_matches)
}

fn partition_orders_by_market_slot(
    bids: Vec<Order>,
    offers: Vec<Order>,
) -> Result<Vec<MatchingData>> {
    let mut order_books: BTreeMap<(String, u64), (Vec<Order>, Vec<Order>)> = BTreeMap::new();

    for bid in bids {
        order_books
            .entry((bid.market_id.clone(), bid.time_slot))
            .or_default()
            .0
            .push(bid);
    }
    for offer in offers {
        order_books
            .entry((offer.market_id.clone(), offer.time_slot))
            .or_default()
            .1
            .push(offer);
    }

    order_books
        .into_iter()
        .map(|((market_id, time_slot), (bids, offers))| {
            MatchingData::new(market_id, time_slot, bids, offers).map_err(|error| anyhow!(error))
        })
        .collect()
}

pub async fn send_settle_batch_transaction(
    evm_node_url: &str,
    settle_order_batch_address: &str,
    matching_engine_private_key: &str,
    matches: Vec<BidOfferMatch>,
    order_lookup: HashMap<String, DbOrderSchema>,
) -> Result<()> {
    if matches.is_empty() {
        info!("No matches to settle");
        return Ok(());
    }

    let settle_order_batch_address =
        Address::from_str(settle_order_batch_address).map_err(|e| {
            anyhow!(
                "Invalid trade settlement address '{}': {}",
                settle_order_batch_address,
                e
            )
        })?;
    let evm_matches = to_evm_matches(matches, &order_lookup)?;

    let provider = Provider::<Ws>::connect(evm_node_url).await?;
    let chain_id = provider.get_chainid().await?.as_u64();
    let wallet = matching_engine_private_key
        .parse::<LocalWallet>()
        .map_err(|e| anyhow!("Invalid matching engine private key: {}", e))?
        .with_chain_id(chain_id);
    let signer_address = wallet.address();
    let client = std::sync::Arc::new(SignerMiddleware::new(provider, wallet));
    let settle_order_batch =
        SettleOrderBatchContract::new(settle_order_batch_address, client.clone());

    let operator_role = keccak256("OPERATOR_ROLE");
    let has_role = settle_order_batch
        .has_role(operator_role, signer_address)
        .call()
        .await?;
    if !has_role {
        warn!(
            "Signer {:?} does not currently have OPERATOR_ROLE in TradeSettlement",
            signer_address
        );
    }

    info!("Submitting {} matches to settleBatch", evm_matches.len());
    let settle_batch_call = settle_order_batch.settle_batch(evm_matches);
    let pending_tx = settle_batch_call.send().await?;
    let tx_hash = pending_tx.tx_hash();
    let receipt = pending_tx.await?;

    match receipt {
        Some(receipt) => {
            if receipt
                .status
                .map(|status| status.as_u64())
                .unwrap_or_default()
                != 1
            {
                return Err(anyhow!(
                    "settleBatch transaction {:?} reverted with status {:?}",
                    tx_hash,
                    receipt.status
                ));
            }
            info!("settleBatch successful. tx={:?}", tx_hash);
            Ok(())
        }
        None => Err(anyhow!(
            "settleBatch transaction {:?} dropped without receipt",
            tx_hash
        )),
    }
}

fn fetch_market_orders(body: Vec<EwdsOrderDto>) -> PreparedOrders {
    let mut open_bids: Vec<Order> = Vec::new();
    let mut open_offers: Vec<Order> = Vec::new();
    let orders: Vec<DbOrderSchema> = body
        .into_iter()
        .map(|o| DbOrderSchema::try_from(o).expect("invalid EwdsOrderDto"))
        .collect();
    let mut by_order_id: HashMap<String, DbOrderSchema> = HashMap::new();

    for db_order_schema in orders
        .into_iter()
        .filter(|order| order.status == OrderStatus::Submitted)
    {
        match convert_db_order_to_canonical(&db_order_schema) {
            Ok(order) => {
                by_order_id.insert(order.order_id.clone(), db_order_schema);
                match order.order_type {
                    OrderEnum::Bid => open_bids.push(order),
                    OrderEnum::Offer => open_offers.push(order),
                }
            }
            Err(e) => {
                error!("Failed to convert DB order to canonical: {:?}", e);
            }
        }
    }

    PreparedOrders {
        open_bids,
        open_offers,
        by_order_id,
    }
}

async fn fetch_open_orders_from_orderbook_service(url: String) -> Result<PreparedOrders, Error> {
    if env::var("OFFCHAIN_STORAGE_TRANSPORT")
        .map(|value| value.eq_ignore_ascii_case("ewds"))
        .unwrap_or(false)
    {
        info!("Fetching orders via EWDS transport");
        return fetch_open_orders_via_ewds(url).await;
    }

    let res = reqwest::get(url).await?;
    info!("Response: {:?} {}", res.version(), res.status());
    info!("Headers: {:#?}\n", res.headers());

    let body = res.json::<Vec<EwdsOrderDto>>().await?;
    info!("Fetched {} total orders from orderbook", body.len());
    Ok(fetch_market_orders(body))
}

async fn fetch_open_orders_via_ewds(fallback_url: String) -> Result<PreparedOrders, Error> {
    fetch_open_orders_via_ewds_query(fallback_url).await
}

async fn fetch_open_orders_via_ewds_query(fallback_url: String) -> Result<PreparedOrders, Error> {
    let query_payload = parse_query_params_from_url(&fallback_url);
    info!("Publishing EWDS orders.query request");
    let ewds_client = EwdsClient::from_env(
        "EWDS_MATCHING_ENGINE_CLIENT_ID",
        "gsymatchingengine",
        60_000,
    );
    let orders: Vec<EwdsOrderDto> = ewds_client
        .query(EwdsOperation::OrdersQuery, query_payload)
        .await?
        .into_iter()
        .map(serde_json::from_value)
        .collect::<Result<Vec<_>, _>>()?;
    info!("Fetched {} total orders from EWDS", orders.len());
    Ok(fetch_market_orders(orders))
}

fn parse_query_params_from_url(url: &str) -> serde_json::Value {
    if let Ok(parsed_url) = reqwest::Url::parse(url) {
        let mut map = serde_json::Map::new();
        for (key, value) in parsed_url.query_pairs() {
            map.insert(
                key.to_string(),
                serde_json::Value::String(value.to_string()),
            );
        }
        return serde_json::Value::Object(map);
    }
    serde_json::json!({})
}

fn parse_bytes16_field(field_name: &str, value: &str) -> Result<[u8; 16]> {
    parse_uuid_or_hex_bytes16(value)
        .ok_or_else(|| anyhow!("{} must be a UUID or 0x-prefixed 16-byte hex", field_name))
}

fn normalize_bytes16_field(field_name: &str, value: &str) -> Result<String> {
    Ok(bytes16_to_hex(parse_bytes16_field(field_name, value)?))
}

fn normalize_optional_bytes16_field(
    field_name: &str,
    value: Option<&str>,
) -> Result<Option<String>> {
    value
        .map(|value| normalize_bytes16_field(field_name, value))
        .transpose()
}

fn convert_requirements(
    requirements: Option<&primitives::db_api_schema::orders::DbRequirements>,
) -> Result<Option<Requirements>> {
    requirements
        .map(|requirements| -> Result<Requirements> {
            Ok(Requirements {
                trading_partner_id: normalize_optional_bytes16_field(
                    "requirements.trading_partner_id",
                    requirements.trading_partner_id.as_deref(),
                )?,
                energy_type: requirements.energy_type.clone(),
                preferred_energy_rate: requirements
                    .preferred_energy_rate
                    .map(|rate| (rate * NODE_FLOAT_SCALING_FACTOR).round() as u64),
            })
        })
        .transpose()
}

fn convert_attributes(
    attributes: Option<&primitives::db_api_schema::orders::DbAttributes>,
) -> Result<Option<Attributes>> {
    attributes
        .map(|attributes| -> Result<Attributes> {
            Ok(Attributes {
                trading_partner_id: normalize_optional_bytes16_field(
                    "attributes.trading_partner_id",
                    attributes.trading_partner_id.as_deref(),
                )?,
                energy_type: attributes.energy_type.clone(),
            })
        })
        .transpose()
}

fn convert_db_order_to_canonical(order: &DbOrderSchema) -> Result<Order> {
    let order_id = normalize_bytes16_field("order_id", &order.order_id)?;
    let market_id = normalize_bytes16_field("market_id", &order.market_id)?;
    let area_uuid = normalize_bytes16_field("area_uuid", &order.area_uuid)?;
    let created_by = normalize_bytes16_field("created_by", &order.created_by)?;
    Ok(match order.order_type {
        OrderEnum::Bid => Order {
            created_by,
            order_id,
            order_type: OrderEnum::Bid,
            status: order.status.clone(),
            area_uuid,
            market_id,
            time_slot: order.time_slot,
            creation_time: order.creation_time,
            energy: (order.energy_kWh * NODE_FLOAT_SCALING_FACTOR).round() as u64,
            energy_rate: (order.energy_rate * NODE_FLOAT_SCALING_FACTOR).round() as u64,
            requirements: convert_requirements(order.requirements.as_ref())?,
            attributes: None,
        },
        OrderEnum::Offer => Order {
            order_id,
            order_type: order.order_type.clone(),
            status: order.status.clone(),
            created_by,
            area_uuid,
            market_id,
            time_slot: order.time_slot,
            creation_time: order.creation_time,
            energy: (order.energy_kWh * NODE_FLOAT_SCALING_FACTOR).round() as u64,
            energy_rate: (order.energy_rate * NODE_FLOAT_SCALING_FACTOR).round() as u64,
            requirements: None,
            attributes: convert_attributes(order.attributes.as_ref())?,
        },
    })
}

fn order_energy_source_preference(order: &DbOrderSchema) -> u8 {
    order
        .requirements
        .as_ref()
        .and_then(|requirements| requirements.energy_type.as_ref())
        .map(energy_type_to_contract)
        .unwrap_or(energy_type_to_contract(&EnergyType::None))
}

fn order_energy_type(order: &DbOrderSchema) -> u8 {
    order
        .attributes
        .as_ref()
        .map(|attributes| energy_type_to_contract(&attributes.energy_type))
        .unwrap_or(energy_type_to_contract(&EnergyType::None))
}

fn to_evm_order_data(order: &DbOrderSchema, expected_type: OrderEnum) -> Result<EvmOrderDataTuple> {
    if order.order_type != expected_type {
        return Err(anyhow!(
            "Order {} type mismatch. Expected {:?}, got {:?}",
            order.order_id,
            expected_type,
            order.order_type
        ));
    }

    Ok((
        parse_bytes16_field("order_id", order.order_id.as_str())?,
        parse_bytes16_field("created_by", order.created_by.as_str())?,
        parse_bytes16_field("market_id", order.market_id.as_str())?,
        order.time_slot,
        order.creation_time,
        (order.energy_kWh * NODE_FLOAT_SCALING_FACTOR).round() as u64,
        (order.energy_rate * NODE_FLOAT_SCALING_FACTOR).round() as u64,
        order_energy_source_preference(order),
        order_energy_type(order),
    ))
}

fn optional_order_id_to_bytes16(order: Option<&Order>) -> Result<[u8; 16]> {
    order
        .map(|order| parse_bytes16_field("residual_order_id", &order.order_id))
        .transpose()
        .map(|value| value.unwrap_or([0u8; 16]))
}

fn derive_trade_id() -> [u8; 16] {
    let uuid = Uuid::new_v4().to_string();
    parse_uuid_or_hex_bytes16(&uuid).expect("Error converting uuid to bytes")
}

fn to_evm_matches(
    matches: Vec<BidOfferMatch>,
    order_lookup: &HashMap<String, DbOrderSchema>,
) -> Result<Vec<EvmMatchTuple>> {
    matches
        .into_iter()
        .map(|item| {
            if item.bid.market_id != item.offer.market_id
                || item.bid.time_slot != item.offer.time_slot
                || item.market_id != item.bid.market_id
                || item.time_slot != item.bid.time_slot
            {
                return Err(anyhow!(
                    "Refusing cross-market/time-slot match between bid {}/{} and offer {}/{}",
                    item.bid.market_id,
                    item.bid.time_slot,
                    item.offer.market_id,
                    item.offer.time_slot
                ));
            }

            let bid_id = item.bid.order_id.to_ascii_lowercase();
            let offer_id = item.offer.order_id.to_ascii_lowercase();
            let bid_order = order_lookup
                .get(&bid_id)
                .ok_or_else(|| anyhow!("Could not find bid order '{}' in lookup map", bid_id))?;
            let offer_order = order_lookup.get(&offer_id).ok_or_else(|| {
                anyhow!("Could not find offer order '{}' in lookup map", offer_id)
            })?;
            let bid_market_id = parse_bytes16_field("bid.market_id", &bid_order.market_id)?;
            let offer_market_id =
                parse_bytes16_field("offer.market_id", &offer_order.market_id)?;
            if bid_market_id != offer_market_id || bid_order.time_slot != offer_order.time_slot {
                return Err(anyhow!(
                    "Refusing DB orders from different market/time-slot boundaries: bid {}/{} and offer {}/{}",
                    bid_order.market_id,
                    bid_order.time_slot,
                    offer_order.market_id,
                    offer_order.time_slot
                ));
            }

            Ok((
                derive_trade_id(),
                to_evm_order_data(bid_order, OrderEnum::Bid)?,
                to_evm_order_data(offer_order, OrderEnum::Offer)?,
                optional_order_id_to_bytes16(item.residual_bid.as_ref())?,
                optional_order_id_to_bytes16(item.residual_offer.as_ref())?,
                U256::from(item.selected_energy),
                U256::from(item.energy_rate),
            ))
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn id(value: u8) -> String {
        format!("0x{value:032x}")
    }

    fn order(id_value: u8, order_type: OrderEnum, market: u8, time_slot: u64) -> Order {
        Order {
            order_id: id(id_value),
            order_type,
            status: OrderStatus::Submitted,
            area_uuid: id(id_value),
            market_id: id(market),
            time_slot,
            creation_time: 1,
            energy: 1,
            energy_rate: 1,
            created_by: id(id_value),
            requirements: None,
            attributes: None,
        }
    }

    #[test]
    fn partitions_orders_by_market_and_time_slot() {
        let order_books = partition_orders_by_market_slot(
            vec![
                order(1, OrderEnum::Bid, 1, 100),
                order(2, OrderEnum::Bid, 1, 200),
                order(3, OrderEnum::Bid, 2, 100),
            ],
            vec![
                order(4, OrderEnum::Offer, 1, 100),
                order(5, OrderEnum::Offer, 1, 200),
                order(6, OrderEnum::Offer, 2, 100),
            ],
        )
        .expect("partitioned orders should be valid");

        assert_eq!(order_books.len(), 3);
        for order_book in order_books {
            assert!(order_book
                .bids()
                .iter()
                .all(|order| order.market_id == order_book.market_id()
                    && order.time_slot == order_book.time_slot()));
            assert!(order_book
                .offers()
                .iter()
                .all(|order| order.market_id == order_book.market_id()
                    && order.time_slot == order_book.time_slot()));
        }
    }

    #[test]
    fn pay_as_clear_calculates_an_independent_price_for_each_order_book() {
        let mut first_bid = order(1, OrderEnum::Bid, 1, 100);
        first_bid.energy_rate = 20;
        let mut first_offer = order(2, OrderEnum::Offer, 1, 100);
        first_offer.energy_rate = 10;
        let mut second_bid = order(3, OrderEnum::Bid, 2, 100);
        second_bid.energy_rate = 40;
        let mut second_offer = order(4, OrderEnum::Offer, 2, 100);
        second_offer.energy_rate = 30;

        let order_books = partition_orders_by_market_slot(
            vec![first_bid, second_bid],
            vec![first_offer, second_offer],
        )
        .expect("partitioned orders should be valid");
        let matches = match_order_books(order_books, &MatchingAlgorithm::PayAsClear)
            .expect("partitioned order books should match");
        let mut clearing_prices = matches
            .iter()
            .map(|item| item.energy_rate)
            .collect::<Vec<_>>();
        clearing_prices.sort_unstable();

        assert_eq!(matches.len(), 2);
        assert_eq!(clearing_prices, vec![10, 30]);
        assert!(matches.iter().all(|item| {
            item.bid.market_id == item.offer.market_id && item.bid.time_slot == item.offer.time_slot
        }));
    }
}
