[package]
name = "e2e-tests"
version = "0.1.0"
authors = ["Grid Singularity <info@gridsingularity.com>"]
edition = "2021"
publish = false

[[bin]]
name = "trade_executor"
path = "src/main.rs"

[dependencies]
cucumber = "0.20"
tokio = { workspace = true, features = ["full"] }
reqwest = { workspace = true }
anyhow = { workspace = true }
ethers = { workspace = true, features = ["ws", "rustls"] }
primitives = { workspace = true }
gsy-community-client = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
hex = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
