[package]
name = "gsy-matching-engine"
version = "0.2.0"
authors = ["Grid Singularity <info@gridsingularity.com>"]
description = "Matching engine client for the Grid Singularity Energy Exchange"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "gsy-matching-engine"

[dependencies]
primitives = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
reqwest = { workspace = true }
ethers = { workspace = true, features = ["ws", "rustls"] }
rand = "0.8"
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true, features = ["log"] }
uuid = { workspace = true }

[dev-dependencies]
ethers-solc = { workspace = true }
tempfile = { workspace = true }
