[package]
name = "gsy-matching-engine"
version = "0.2.0"
authors = ["Grid Singularity <info@gridsingularity.com>"]
description = "Matching engine client for the Grid Singularity Energy Exchange"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "gsy-matching-engine"

[dependencies]
primitives = { path = "../primitives" }
anyhow = "1"
clap = { version = "4", features = ["derive"]}
reqwest = { version = "0.11", features = ["json"] }
ethers = { version = "2.0.14", features = ["ws", "rustls"] }
rand = "0.8"
serde_json = { version = "1.0"}
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1", features = ["log"] }
uuid = { version = "1.12.1", features = ["v4"] }

[dev-dependencies]
ethers-solc = "2.0.14"
tempfile = "3"
