FROM rust:1.82

WORKDIR /app

COPY gsy-matching-engine/Cargo.toml /app/gsy-matching-engine/
COPY offchain-primitives/Cargo.toml /app/offchain-primitives/

COPY gsy-matching-engine/ ./gsy-matching-engine/
COPY offchain-primitives/ ./offchain-primitives/

WORKDIR /app/gsy-matching-engine

RUN cargo build

CMD ["cargo", "test", "--all-features"]