[package]
name = "gsy-execution-engine"
version = "0.1.0"
authors = ["Grid Singularity <info@gridsingularity.com>"]
edition = "2021"
description = "Execution Engine for the Grid Singularity Energy Exchange"

[dependencies]
primitives = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
ethers = { workspace = true, features = ["ws", "rustls"] }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true, features = ["log"] }
uuid = { workspace = true }

[dev-dependencies]
ethers-solc = { workspace = true }
tempfile = { workspace = true }

[[bin]]
name = "gsy-execution-engine"
path = "src/main.rs"
