application_host: "0.0.0.0"
application_port: "9876"
database_host: "localhost"
database_username: "gsy"
database_password: "gsy"
database_name: "launchpad"
database_url_scheme: "mongodb"
jwt_secret: "test_secret"
