[package]
name = "gsy-offchain-primitives"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
codec = { package = "parity-scale-codec", version = "3.6.9", default-features = false, features = ["derive", "full", "bit-vec"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0"}
subxt = { version = "0.35.1", features = ["substrate-compat"] }
