[package]
name = "gsy-community-client"
version = "0.1.0"
edition = "2021"


[[bin]]
path = "src/main.rs"
name = "gsy-community-client"

[lib]
name = "gsy_community_client"
path = "src/lib.rs"

[dependencies]
primitives = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
ethers = { workspace = true, features = ["ws", "rustls"] }
tracing = { workspace = true, features = ["log"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
blake2-rfc = { version = "0.2.18", default-features = false }
uuid = { workspace = true }
serial_test = "3"

[dev-dependencies]
wiremock = "0.6.5"
httpmock = "0.8.0-alpha.1"
tracing-subscriber = { workspace = true }
ethers-solc = { workspace = true }
tempfile = { workspace = true }
