use crate::helpers::{init_app, stop_app};
use actix_web::web;
use gsy_offchain_primitives::db_api_schema::orders::{OrderStatus, DbOrderSchema, OrderEnum};
use mongodb::bson::Bson;
use std::collections::HashMap;


#[tokio::test]
async fn subscribe_return_a_200_for_valid_form_data() {
    let app = init_app().await;
    let address = app.address.clone();

    let market_id = "market_id".to_string();
    let area_id = "area_id".to_string();

    let order = DbOrderSchema {
        order_id: "order_id".to_string(), // order._id is autogenerated, will not set it in the tests.
        status: OrderStatus::Expired,
        order_type: OrderEnum::Bid,
        created_by: "buyer".to_string(),
        energy_kWh: 100.0,
        energy_rate: 10.0,
        area_uuid: area_id,
        market_id,
        time_slot: 1,
        creation_time: 1677453190,
        requirements: None,
        attributes: None,
    };

    let orderlist = vec![order.clone()];

    let client = reqwest::Client::new();
    let resp = client
        .post(&format!("{}/orders", &address))
        .header("Content-Type", "application/json")
        .json(&orderlist)
        .send()
        .await
        .expect("Failed to execute request.");

    let status = resp.status();
    let response = resp.json::<HashMap<usize, Bson>>().await.unwrap();

    let resp_order_id = response.get(&0).unwrap();

    let db = web::Data::new(app.db_wrapper.clone());

    assert_eq!(200, status.as_u16());

    let update_result = db
        .get_ref()
        .orders()
        .update_order_status_by_id(resp_order_id, OrderStatus::Executed)
        .await
        .unwrap();
    assert_eq!(update_result.modified_count, 1);
    let updated_order = db
        .get_ref()
        .orders()
        .get_order_by_id(resp_order_id)
        .await
        .unwrap();
    assert_eq!(updated_order.unwrap().status, OrderStatus::Executed);
    stop_app(app).await;
}

#[tokio::test]
async fn subscribe_return_a_400_when_data_is_missing() {
    let app = init_app().await;
    let address = app.address.clone();

    let client = reqwest::Client::new();
    let test_cases = vec![("test", "err"), ("test2", "err")];

    for (invalid_body, error_message) in test_cases {
        let resp = client
            .post(&format!("{}/orders", &address))
            .header("Content-Type", "application/json")
            .body(invalid_body)
            .send()
            .await
            .expect("Failed to execute request.");
        assert_eq!(
            400,
            resp.status().as_u16(),
            "The API did not fail with 400 Bad Request when the payload was {}.",
            error_message
        );
    }
    stop_app(app).await;
}
