name: GSY Node Security scheduled audit
on:
  push:
    paths:
      - '**/gsy-node/Cargo.toml'
      - '**/gsy-node/Cargo.lock'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: cd $GITHUB_WORKSPACE/gsy-node
      - uses: rustsec/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore: RUSTSEC-2025-0009,RUSTSEC-2025-0118,RUSTSEC-2026-0006
